### ISSUE TITLE
mesh:setTexture(texture)

### ISSUE THREAD

**Issue by revolucas** [excessive/love3d-demos#1]
Do textured meshes work? I've tried setting the texture of the model's mesh but it's still white. 

Basically I added the texture similarly to how it's exampled for the iqm module: https://devhub.io/repos/excessive-iqm

I can confirm the texture is actually loaded using love.graphics.draw.

**Comment by shakesoda** [comment]
yes, textures work just fine. remember to sample the texture in your shader (as per [the docs](https://love2d.org/wiki/love.graphics.newShader))

**Comment by revolucas** [comment]
Oh, okay, I just add  vec4 color  = texture2D(_tex, _uv) to effects

Thanks for the help.
